apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flaskdep
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 2
  selector:
    matchLabels:
      app: flaskdep
  template:
    metadata:
      labels:
        app: flaskdep
    spec:
      containers:
      - name: flask-container
        image: siradjedd/basic-flask-app:latest
        ports:
        - containerPort: 5000