apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Siradjedd/argocd-cd-pipeline.git
    targetRevision: HEAD
    path: dev
      

  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - Validate=false
      - CreateNamespace=true