apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-argo-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: siradjedd/basic-flask-app:~2.0
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default
  source:
    repoURL: https://github.com/Siradjedd/argocd-cd-pipeline.git
    targetRevision: HEAD
    path: dev-stage
      

  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - Validate=false
      - CreateNamespace=true

